name: stylelint
on:
  pull_request:
    branches: [ master ]
jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-pr-check
